server:
  port: 3232

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dzy32/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
  application:
    name: config-center
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
