server:
  port: 3232

spring:
  cloud:
    config:
      server:
        git:
#          使用https 连接git 使用ssh失败，似乎配值比较麻烦，以后补坑
          uri: https://github.com/dzy32/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
  application:
    name: config-center
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7001/eureka/
