server:
  port: 8500
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        rabbit1:
          type: rabbit
          enviroment:
            spring:
              rabbitmq:
                host: 10.100.60.103
                port: 5672
                username: guest
                password: guest
      bindings:
        ouput:
          destination: studyExchange
          binder: rabbit1
          content-type: application/json


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7001/eureka/
    fetch-registry: true
    register-with-eureka: true

