server:
  port: 8500
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages #要和output的destination一致, 这样才能将队列和写入消息的exchange关联起来
          binder: local_rabbit
          group: logMessageConsumers
        output:
          destination: queue.log.messages
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.100.60.103
                port: 5672
                username: guest
                password: guest
                virtual-host: /
  application:
    name: stream-provider
  rabbitmq:
    host: 10.100.60.103
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7001/eureka/
    fetch-registry: true
    register-with-eureka: true

