server:
  port: 8601
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.stream.messages
          binder: rabbit1
          group: stream # 分组从而解决重复消费和持计化
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.100.60.103
                port: 5672
                username: guest
                password: guest
                virtual-host: /
        rabbit2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.100.60.103
                port: 5673
                username: guest
                password: guest
  application:
    name: stream-consumer
  rabbitmq:
    host: 10.100.60.103
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7001/eureka/
    fetch-registry: true
    register-with-eureka: true

