spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描
        #直至找到未被占用的端口
        port: 8719
  application:
    name: service-nacos-payment
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: '*'
